### ISSUE TITLE
The 'ansible_local' provisioner could not be found

### ISSUE THREAD

**Issue by luandro** [WeLikeGraphQL/wordpress-graphql-api-example#1]
Just got a fresh clone. When running `vagrant up --provision` I get:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'ansible_local' provisioner could not be found.
```

**Comment by graphan** [comment]
@luandro, sorry for the late response.
What vagrant version do you have? Be sure, to have >=1.8, because ansible_local is available from [Vagrant 1.8](http://www.jeffgeerling.com/blog/use-vagrant-18s-new-ansiblelocal-provisioner)
I will update Readme.
