### ISSUE TITLE
ERROR with Docker deploy

### ISSUE THREAD

**Issue by luandro** [WeLikeGraphQL/wordpress-graphql-api-example#2]
Got this when trying to run `docker-compose up` on a CentOS server with Docker:

```
ERROR: Volume wordpress-data specifies nonexistent driver local-persist
```

**Comment by graphan** [comment]
Sorry for the late response once again. I had problems with my email.

Now it should work, I just forgot to add information about [local-persist](https://github.com/WeLikeGraphQL/wordpress-graphql-api-example#docker-for-linux). There might be some other errors on different machines, so do not hesitate to open an issue if you find something.
